services:
  web:
    build:
      context: ./mycrm/
    command: gunicorn mycrm.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres_db
    volumes:
      - ./mycrm/:/usr/src/app/
      - static_files:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./.env

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/static

volumes:
  static_files:
  pg_data: