# Generated by Django 5.0 on 2024-01-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_alter_customer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='lead',
        ),
    ]
