# Generated by Django 5.0 on 2024-01-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_rename_customer_customer_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
