# Generated by Django 5.0 on 2024-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_remove_contract_validity_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='full_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
