# Generated by Django 5.0 on 2024-01-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_alter_contract_document_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='service',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign',
        ),
    ]
