# Generated by Django 5.0 on 2024-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_remove_lead_full_name_lead_first_name_lead_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
