# Generated by Django 5.0 on 2024-01-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_remove_advertising_service_remove_lead_campaign'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.DeleteModel(
            name='Advertising',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
