# Generated by Django 5.0 on 2024-01-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_customer_lead_delete_advertising_delete_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='service',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
