# Generated by Django 5.0 on 2024-01-15 11:51

import customers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_name'),
        ('customers', '0001_initial'),
        ('leads', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.OneToOneField(limit_choices_to=customers.models.get_available_contracts, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.OneToOneField(limit_choices_to=models.Q(('customer__isnull', True)), on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
