# Generated by Django 5.0 on 2024-01-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_name'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
    ]
