# Generated by Django 5.0 on 2024-01-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['last_name'], 'verbose_name': 'lead'},
        ),
    ]
